# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; during revision
# generate-vsn, the % (rev) s etc. syntax is used to create the
# filename.
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, space-delimited, or empty.  
# This is where the models and env.py are located.
# We set this to the current directory (where app/ is)
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library.
# timezone =

# max length of characters to prepend to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, paths separated by spaces may be
# specified here.
# version_locations = %(here)s/bar/versions %(here)s/bat/versions

# version path separator; as above, default is space.
# version_path_separator = ;

# the framework used to emit logging calls
# log_config_file = alembic.ini


[post_write_hooks]
# post_write_hooks defines scripts to run after a revision file is generated.
# Commented out since black is not installed in the container.
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79


[logging]
# logging configuration
default_handler = console


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
