""" Add fields attachments in users

Revision ID: 24a62affd8fe
Revises: 4d2638a2aa3d
Create Date: 2026-05-01 05:06:27.394728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a62affd8fe'
down_revision: Union[str, None] = '4d2638a2aa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
