""" Add Relationship between Notifications to Ticket.

Revision ID: 2de6fd745641
Revises: 24a62affd8fe
Create Date: 2026-05-01 16:08:04.138669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de6fd745641'
down_revision: Union[str, None] = '24a62affd8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
