""" Initial migrations created to models.

Revision ID: 4d2638a2aa3d
Revises: c8e4f662e5a5
Create Date: 2026-04-29 23:16:28.182693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2638a2aa3d'
down_revision: Union[str, None] = 'c8e4f662e5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
