""" Migration to Models to Ai chat.

Revision ID: 8e8c7aaf5d79
Revises: 2de6fd745641
Create Date: 2026-05-03 02:34:31.263801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8c7aaf5d79'
down_revision: Union[str, None] = '2de6fd745641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
